#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by worktree-flow.
# This repository owns this script from now on.
# Update it if test verification needs repository-specific behavior.
# ecosystem: maven
# source: maven-wrapper
# command: ./mvnw test

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

./mvnw test
